### ISSUE TITLE
Authorization Error when using the example

### ISSUE THREAD

**Issue by abedmurrar** [Rainbow-CPaaS/passport-rainbow-oauth2#2]
When using the example provided and changing the APP ID and APP SECRET to the ones i use in production i get an Authorization error

I Just cloned the repo, and changed the configuration that i have to change and tested it, it leads me to rainbow Auth2 screen and i use my email and my password then it leads me to this error.
```
AuthorizationError: Invalid client: missing client `redirectUri`
    at Strategy.OAuth2Strategy.authenticate (C:\Users\amurrar\Dev\passport-rainbow-oauth2\node_modules\passport-oauth2\lib\strategy.js:137:25)
    at Strategy.authenticate (C:\Users\amurrar\Dev\passport-rainbow-oauth2\lib\oauth2.js:62:41)
    at attempt (C:\Users\amurrar\Dev\passport-rainbow-oauth2\example\node_modules\passport\lib\middleware\authenticate.js:361:16)
    at authenticate (C:\Users\amurrar\Dev\passport-rainbow-oauth2\example\node_modules\passport\lib\middleware\authenticate.js:362:7)
    at Layer.handle [as handle_request] (C:\Users\amurrar\Dev\passport-rainbow-oauth2\example\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\amurrar\Dev\passport-rainbow-oauth2\example\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\amurrar\Dev\passport-rainbow-oauth2\example\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\amurrar\Dev\passport-rainbow-oauth2\example\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\amurrar\Dev\passport-rainbow-oauth2\example\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\amurrar\Dev\passport-rainbow-oauth2\example\node_modules\express\lib\router\index.js:335:12)
```

**Comment by zucher** [comment]
Hi @abedmurrar did you fill the redirecturl under the Rainbow hub for your application?
